import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  achievements,
  challengeQuestions,
  challengeSettings,
  lessonQuestions,
  worldOne,
  type ChallengeQuestion,
  type LessonExercise,
} from "../lib/learning-data.ts";

type RawSql = {
  kind: "raw";
  value: string;
};

type SqlValue = string | number | boolean | null | undefined | RawSql;

const contentStatus = "PUBLISHED";
const outputFile = resolve(process.cwd(), "supabase-seed-content.sql");

const lines: string[] = [
  "-- Generated by prisma/generate-seed-sql.ts.",
  "-- This file seeds learning content only. It does not include user data or credentials.",
  "BEGIN;",
  "",
];

addInsert(
  "World",
  {
    id: contentId("world", worldOne.id),
    slug: worldOne.id,
    number: worldOne.number,
    title: worldOne.title,
    subtitle: worldOne.subtitle,
    description: worldOne.description,
    xpReward: worldOne.xp,
    status: contentStatus,
    metadata: json({
      bossTitle: worldOne.bossTitle,
      bossDescription: worldOne.bossDescription,
      dailyChallengeTitle: worldOne.dailyChallengeTitle,
      dailyChallengeDescription: worldOne.dailyChallengeDescription,
      progressPercent: worldOne.progressPercent,
      profileProgressPercent: worldOne.profileProgressPercent,
      dashboardProgressPercent: worldOne.dashboardProgressPercent,
    }),
  },
  ["slug"],
  ["number", "title", "subtitle", "description", "xpReward", "status", "metadata"],
);

for (const [index, stageData] of worldOne.stages.entries()) {
  const stageNumber = Number.parseInt(stageData.number, 10);

  addInsert(
    "Stage",
    {
      id: contentId("stage", worldOne.id, stageData.id),
      worldId: selectWorldId(worldOne.id),
      slug: stageData.id,
      number: Number.isNaN(stageNumber) ? index + 1 : stageNumber,
      title: stageData.title,
      description: stageData.description,
      xpReward: stageData.xp,
      status: contentStatus,
      isBossStage: stageData.boss ?? false,
      metadata: json({
        displayNumber: stageData.number,
        learningStatus: stageData.status,
        locked: stageData.locked ?? false,
      }),
    },
    ["worldId", "slug"],
    ["number", "title", "description", "xpReward", "status", "isBossStage", "metadata"],
  );
}

for (const lessonData of worldOne.lessons) {
  addInsert(
    "Lesson",
    {
      id: contentId("lesson", worldOne.id, lessonData.id),
      worldId: selectWorldId(worldOne.id),
      stageId: selectStageId(worldOne.id, lessonData.stageId),
      slug: lessonData.id,
      number: Number.parseInt(lessonData.number, 10),
      title: lessonData.title,
      description: lessonData.description,
      xpReward: lessonData.xpReward,
      status: contentStatus,
      vocabulary: json(lessonData.vocabulary),
      metadata: json({
        learningStatus: lessonData.status,
        xp: lessonData.xp,
        locked: lessonData.locked ?? false,
      }),
    },
    ["worldId", "slug"],
    ["stageId", "number", "title", "description", "xpReward", "status", "vocabulary", "metadata"],
  );

  for (const [exerciseIndex, exercise] of lessonData.exercises.entries()) {
    addInsert(
      "Exercise",
      {
        id: contentId("exercise", lessonData.id, exercise.id),
        lessonId: selectLessonId(worldOne.id, lessonData.id),
        slug: exercise.id,
        type: exercise.type,
        prompt: exercise.prompt,
        content: json(getExerciseContent(exercise)),
        answerKey: json(getExerciseAnswerKey(exercise)),
        explanation: exercise.explanation,
        points: exercise.points,
        order: exerciseIndex + 1,
        status: contentStatus,
      },
      ["lessonId", "slug"],
      ["type", "prompt", "content", "answerKey", "explanation", "points", "order", "status"],
    );
  }
}

addInsert(
  "Challenge",
  {
    id: contentId("challenge", worldOne.id, "world-1-boss"),
    worldId: selectWorldId(worldOne.id),
    stageId: selectStageId(worldOne.id, "boss-level"),
    slug: "world-1-boss",
    title: worldOne.bossTitle,
    description: worldOne.bossDescription,
    type: "boss",
    xpReward: Math.round(totalChallengePoints(challengeQuestions) / 10),
    passScore: challengeSettings.passScore,
    content: json({
      questions: challengeQuestions,
      settings: challengeSettings,
    }),
    status: contentStatus,
    metadata: json({
      source: "challengeQuestions",
      startingHearts: challengeSettings.startingHearts,
    }),
  },
  ["worldId", "slug"],
  ["stageId", "title", "description", "type", "xpReward", "passScore", "content", "status", "metadata"],
);

addInsert(
  "Challenge",
  {
    id: contentId("challenge", worldOne.id, "world-1-daily-review"),
    worldId: selectWorldId(worldOne.id),
    stageId: null,
    slug: "world-1-daily-review",
    title: worldOne.dailyChallengeTitle,
    description: worldOne.dailyChallengeDescription,
    type: "daily",
    xpReward: lessonQuestions.length * 10,
    passScore: null,
    content: json({
      questions: lessonQuestions,
    }),
    status: contentStatus,
    metadata: json({
      source: "lessonQuestions",
    }),
  },
  ["worldId", "slug"],
  ["stageId", "title", "description", "type", "xpReward", "passScore", "content", "status", "metadata"],
);

for (const achievement of achievements) {
  addInsert(
    "Achievement",
    {
      id: contentId("achievement", achievement.id),
      slug: achievement.id,
      title: achievement.title,
      description: achievement.description,
      xpReward: 0,
      status: contentStatus,
      criteria: json({
        learningStatus: achievement.status,
      }),
      metadata: null,
    },
    ["slug"],
    ["title", "description", "xpReward", "status", "criteria", "metadata"],
  );
}

lines.push("COMMIT;", "");

writeFileSync(outputFile, lines.join("\n"), "utf8");

console.log(`Generated ${outputFile}`);

function addInsert(
  table: string,
  row: Record<string, SqlValue>,
  conflictColumns: string[],
  updateColumns: string[],
) {
  const insertColumns = [...Object.keys(row), "createdAt", "updatedAt"];
  const insertValues = [...Object.values(row), raw("now()"), raw("now()")];
  const updates = [...updateColumns.map((column) => `${identifier(column)} = EXCLUDED.${identifier(column)}`), `"updatedAt" = now()`];

  lines.push(`INSERT INTO ${identifier(table)} (${insertColumns.map(identifier).join(", ")})`);
  lines.push(`VALUES (${insertValues.map(sql).join(", ")})`);
  lines.push(`ON CONFLICT (${conflictColumns.map(identifier).join(", ")}) DO UPDATE SET`);
  lines.push(`  ${updates.join(",\n  ")};`);
  lines.push("");
}

function getExerciseContent(exercise: LessonExercise) {
  if (exercise.type === "multipleChoice") {
    return {
      display: exercise.display,
      options: exercise.options,
      correctAnswer: exercise.correctAnswer,
    };
  }

  if (exercise.type === "fillBlank") {
    return {
      beforeBlank: exercise.beforeBlank,
      afterBlank: exercise.afterBlank,
      options: exercise.options,
      correctAnswer: exercise.correctAnswer,
    };
  }

  if (exercise.type === "sentenceOrder") {
    return {
      translation: exercise.translation,
      words: exercise.words,
      correctOrder: exercise.correctOrder,
    };
  }

  if (exercise.type === "matching") {
    return {
      pairs: exercise.pairs,
      englishOptions: exercise.englishOptions,
    };
  }

  return {
    situation: exercise.situation,
    options: exercise.options,
    correctAnswer: exercise.correctAnswer,
  };
}

function getExerciseAnswerKey(exercise: LessonExercise) {
  if (exercise.type === "matching") {
    return {
      pairs: exercise.pairs,
    };
  }

  if (exercise.type === "sentenceOrder") {
    return {
      correctOrder: exercise.correctOrder,
    };
  }

  return {
    correctAnswer: exercise.correctAnswer,
  };
}

function totalChallengePoints(questions: ChallengeQuestion[]) {
  return questions.reduce((sum, question) => sum + question.points, 0);
}

function contentId(...parts: string[]) {
  return parts.join(":");
}

function selectWorldId(slug: string) {
  return raw(`(SELECT "id" FROM "World" WHERE "slug" = ${stringLiteral(slug)})`);
}

function selectStageId(worldSlug: string, stageSlug: string) {
  return raw(
    `(SELECT "Stage"."id" FROM "Stage" INNER JOIN "World" ON "World"."id" = "Stage"."worldId" WHERE "World"."slug" = ${stringLiteral(
      worldSlug,
    )} AND "Stage"."slug" = ${stringLiteral(stageSlug)})`,
  );
}

function selectLessonId(worldSlug: string, lessonSlug: string) {
  return raw(
    `(SELECT "Lesson"."id" FROM "Lesson" INNER JOIN "World" ON "World"."id" = "Lesson"."worldId" WHERE "World"."slug" = ${stringLiteral(
      worldSlug,
    )} AND "Lesson"."slug" = ${stringLiteral(lessonSlug)})`,
  );
}

function json(value: unknown) {
  return raw(`${stringLiteral(JSON.stringify(value))}::jsonb`);
}

function sql(value: SqlValue) {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (isRawSql(value)) {
    return value.value;
  }

  if (typeof value === "number") {
    return Number.isFinite(value) ? value.toString() : "NULL";
  }

  if (typeof value === "boolean") {
    return value ? "TRUE" : "FALSE";
  }

  return stringLiteral(value);
}

function stringLiteral(value: string) {
  return `'${value.replaceAll("'", "''").replaceAll("\u0000", "")}'`;
}

function identifier(value: string) {
  return `"${value.replaceAll('"', '""')}"`;
}

function raw(value: string): RawSql {
  return {
    kind: "raw",
    value,
  };
}

function isRawSql(value: SqlValue): value is RawSql {
  return typeof value === "object" && value !== null && value.kind === "raw";
}
